# Generated by Django 6.0 on 2025-12-22 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст Новости')),
                ('feature', models.BooleanField(default=False, verbose_name='В слайдере')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('created_ta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
