# Generated by Django 6.0 on 2025-12-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feature',
        ),
    ]
