# Generated by Django 6.0 on 2025-12-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getpost', '0002_remove_post_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
