# Generated by Django 6.0 on 2025-12-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getpost', '0004_remove_post_id_post_id_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_post',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
